### ISSUE TITLE
font spacing, overlapping characters

### ISSUE THREAD

**Issue by SimonAB** [iaolo/iA-Fonts#19]
In various situations, macOS seems to not know where letters end -- e.g. wrapping a paragraph within a window's edge, or as in the screen capture below, converting an url to an active link. It looks like the extra half spaces are being ignored. 

<img width="495" alt="image" src="https://user-images.githubusercontent.com/537780/34573907-acf94896-f16d-11e7-91ad-3163030a5b7d.png">

**Comment by roelvangils** [comment]
That's the reason why I'm not using it right now. It's bug this font has. The overlapping also happens when resizing windows (I used it in Mail.app, for composing mails). It's unpredictable, but happens a lot when you type a lot. Also, sometimes you end up with two spaces without knowing it etc.

I really want to use this font for my daily writing, because I like the extra wide w and m etc. For now, I have to switch back IBM Plex Mono.

**Comment by iaolo** [comment]
Yeah, on the OS level, it somehow it gets identified as mono and gets forced into the mono grid. I'll look into it.

**Comment by iaolo** [comment]
Should work now
