### ISSUE TITLE
Greek is missing from iA Writer Mono

### ISSUE THREAD

**Issue by nicksherman** [iaolo/iA-Fonts#31]
I'm guessing this wasn't intentional since the Duo and Quattro fonts have it?

**Comment by iaolo** [comment]
This was intentional. I think Greek mono, especially polytonic Greek mono, doesn't make much sense.

**Comment by alehandrof** [comment]
FWIW, I often write prose in Sublime Text (which doesn't support variable width fonts well) and use iA Writer Mono when using it full screen. (Otherwise, I use Iosevka). I'm a Greek speaker, so I often write in Greek. Admittedly, I'm a niche case. I'm not advocating for the inclusion of Greek in iA Writer Mono, just pointing out what case looks like where it makes sense.
